// Generated by First Folio.

// State readers used by page-header and page-footer format tokens.
// The initial value is empty so [part]/[chapter] render blank on pages preceding the first heading.
#let _folio_part_state_init = state("folio-current-part", "")
#let _folio_chapter_state_init = state("folio-current-chapter", "")

// Skip records for the running header/footer on part/chapter title pages. Each part/chapter
// macro records the page number it lands on if its skip-header / skip-footer flag is true;
// the header/footer context reads the final list via `.final()` and hides the running band
// only on those specific pages. This keeps subsequent body pages of a multi-page chapter
// showing their normal running header and footer. The default value `()` is provided at the
// call sites (both `.final()` and `.update()`) so no explicit initialization is needed here.

// Physical vs display page counters. `counter(page)` is left as Typst's built-in physical
// page counter, incrementing on every page and NEVER reset. All parity checks
// (calc.odd for header/footer alignment; pagebreak(to: "odd") for enforce-right; skip-list
// membership) use this physical counter so odd = recto = right-hand from the reader's view,
// matching the standard book convention where page 1 (title) is always a recto. A separate
// `folio-page-offset` state records the physical counter value at the first body block
// (part or chapter with first=true) minus one, so displayed page numbers can start at 1
// for the body while the underlying counter continues from the title-page count.
#let folio-display-page() = context {
  let physical = counter(page).at(here()).first()
  let offset = state("folio-page-offset", 0).final()
  str(physical - offset)
}

// A blank page macro used to satisfy folio.manuscript.{part,chapter}.blank-page-{before,after}.
// A weak pagebreak avoids doubling with an adjacent hard break; the empty page() scope removes
// numbering, header, and footer so the blank page is visually blank and unnumbered.
#let folio-blank-page() = {
  pagebreak(weak: true)
  page(numbering: none, header: none, footer: none)[]
}

#let folio-section(body) = {
  v(1.2em)
  align(left)[#text(
    font: "{{.Config.Folio.Manuscript.HeadingFont}}",
    size: {{.Config.Folio.Manuscript.HeadingFontSize}},
    weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
  )[#heading(level: 3, outlined: {{.Config.Folio.Manuscript.TOC.IncludeSections}})[#body]]]
  v(0.4em)
}

#let folio-part(first: false, skip-header: false, skip-footer: false, body) = {
  state("folio-current-part").update(body)
  state("folio-current-chapter").update([])
  if not first and {{.Config.Folio.Manuscript.Part.PageBreakBefore}} {
    pagebreak(weak: true)
  }
  // Seed the display-page offset at the first body block so page tokens start at 1.
  if first {
    context {
      state("folio-page-offset", 0).update(counter(page).at(here()).first() - 1)
    }
  }
  // After any pagebreak, record this heading's page number in the skip lists
  // when its flags are set. The header/footer context checks membership.
  context {
    let pg = counter(page).at(here()).first()
    if skip-header {
      state("folio-skip-header-pages", ()).update(pages => pages + (pg,))
    }
    if skip-footer {
      state("folio-skip-footer-pages", ()).update(pages => pages + (pg,))
    }
  }
  align({{.Config.Folio.Manuscript.Part.Align}} + {{.PartVertical}})[
    #text(
      font: "{{.Config.Folio.Manuscript.HeadingFont}}",
      size: {{.Config.Folio.Manuscript.HeadingFontSize}},
      weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
    )[
      #heading(level: 1, outlined: {{.Config.Folio.Manuscript.TOC.IncludeParts}})[#body]
    ]
  ]
}

#let folio-chapter(first: false, skip-header: false, skip-footer: false, body) = {
  // Update state BEFORE pagebreak so the new chapter page's header/footer context sees the
  // new chapter title (state updates take effect from their source position onward, and the
  // pagebreak's new page is a later source position).
  state("folio-current-chapter").update(body)
  if not first and {{.Config.Folio.Manuscript.Chapter.PageBreakBefore}} {
    pagebreak(weak: true)
  }
  // Seed the display-page offset at the first body block so page tokens start at 1.
  if first {
    context {
      state("folio-page-offset", 0).update(counter(page).at(here()).first() - 1)
    }
  }
  context {
    let pg = counter(page).at(here()).first()
    if skip-header {
      state("folio-skip-header-pages", ()).update(pages => pages + (pg,))
    }
    if skip-footer {
      state("folio-skip-footer-pages", ()).update(pages => pages + (pg,))
    }
  }
  v({{.ChapterPosition}})
  align({{.Config.Folio.Manuscript.Chapter.Align}})[
    #text(
      font: "{{.Config.Folio.Manuscript.HeadingFont}}",
      size: {{.Config.Folio.Manuscript.HeadingFontSize}},
      weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
    )[
      #heading(level: 2, outlined: {{.Config.Folio.Manuscript.TOC.IncludeChapters}})[#body]
    ]
  ]
  v({{.Config.Folio.Manuscript.Chapter.SpaceAfter}})
}

#let folio-scene-break() = {
  v(1em)
  align(center)[{{.SceneBreakMarker}}]
  v(1em)
}

#let folio-code(body) = {
  block(
    above: {{.Config.Folio.Manuscript.CodeBlock.SpaceBefore}},
    below: {{.Config.Folio.Manuscript.CodeBlock.SpaceAfter}},
  )[
    #text(
      font: "{{.Config.Folio.Manuscript.MonoFont}}",
      size: {{.Config.Folio.Manuscript.MonoFontSize}},
      weight: "{{.Config.Folio.Manuscript.MonoFontWeight}}",
    )[#body]
  ]
}

#show list: it => {
  v({{.Config.Folio.Manuscript.List.SpaceBefore}})
  it
  v({{.Config.Folio.Manuscript.List.SpaceAfter}})
}

#show enum: it => {
  v({{.Config.Folio.Manuscript.List.SpaceBefore}})
  it
  v({{.Config.Folio.Manuscript.List.SpaceAfter}})
}

#show figure.where(kind: table): it => {
  v({{.Config.Folio.Manuscript.Table.SpaceBefore}})
  it
  v({{.Config.Folio.Manuscript.Table.SpaceAfter}})
}

#show strong: it => text(weight: "bold")[#it.body]
#show emph: it => text(style: "italic")[#it.body]

#show raw.where(block: true): it => block(
  above: {{.Config.Folio.Manuscript.CodeBlock.SpaceBefore}},
  below: {{.Config.Folio.Manuscript.CodeBlock.SpaceAfter}},
)[#text(
  font: "{{.Config.Folio.Manuscript.MonoFont}}",
  size: {{.Config.Folio.Manuscript.MonoFontSize}},
  weight: "{{.Config.Folio.Manuscript.MonoFontWeight}}",
)[#it]]

#show raw.where(block: false): it => text(
  font: "{{.Config.Folio.Manuscript.MonoFont}}",
  size: {{.Config.Folio.Manuscript.MonoFontSize}},
  weight: "{{.Config.Folio.Manuscript.MonoFontWeight}}",
)[#it]

#set page(
  {{if .PageSpec.Custom}}width: {{.PageSpec.Width}}, height: {{.PageSpec.Height}},{{else}}paper: "{{.PageSpec.Named}}",{{end}}
  margin: {{.Config.Folio.Manuscript.Margin}},
  numbering: {{if .Config.Folio.Manuscript.TitlePage.PageNumber}}"1"{{else}}none{{end}},
)

#set text(
  font: "{{.Config.Folio.Manuscript.Font}}",
  size: {{.Config.Folio.Manuscript.FontSize}},
  weight: "{{.Config.Folio.Manuscript.FontWeight}}",
)

{{if and (not .IsUS) .Config.Folio.Manuscript.TitlePage.Enabled}}
#set page(
  footer: [
    #grid(
      columns: (1fr, 1fr, 1fr),
      align: (left, {{.FooterGroupAlignExpr}}, right),
      [
        {{if and .Config.Folio.Manuscript.TitlePage.IncludeVersion (not .VersionAlignExpr)}}#text(font: "{{.Config.Folio.Manuscript.VersionFont}}", size: {{.Config.Folio.Manuscript.VersionFontSize}}, weight: "{{.Config.Folio.Manuscript.VersionFontWeight}}")[{{.Meta.Version}}]{{end}}
      ],
      [
        {{if and .Config.Folio.Manuscript.TitlePage.IncludeWordCount (not .WordCountAlignExpr)}}#text(font: "{{.Config.Folio.Manuscript.WordCountFont}}", size: {{.Config.Folio.Manuscript.WordCountFontSize}}, weight: "{{.Config.Folio.Manuscript.WordCountFontWeight}}")[
          #if "{{.Meta.WordCount}}" != "" [{{.Meta.WordCount}}]
        ]{{end}}
      ],
      [
        {{if and .Config.Folio.Manuscript.TitlePage.IncludeDate (not .DateAlignExpr)}}#text(font: "{{.Config.Folio.Manuscript.DateFont}}", size: {{.Config.Folio.Manuscript.DateFontSize}}, weight: "{{.Config.Folio.Manuscript.DateFontWeight}}")[{{.Meta.Date}}]{{end}}
      ],
    )
  ],
)
{{end}}

{{if .Config.Folio.Manuscript.TitlePage.Enabled}}
{{if .HasContact}}#place({{if .ContactAlignExpr}}{{.ContactAlignExpr}}{{else}}top + left{{end}}{{if .ContactFloatable}}, float: true{{else}}{{if not .ContactAlignExpr}}, float: true{{end}}{{end}})[
  #stack(
    dir: ttb,
    spacing: 0.25em,
    {{if and .Config.Folio.Manuscript.TitlePage.IncludeContactName .Meta.ContactName}}[#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}}, weight: "{{.Config.Folio.Manuscript.ContactFontWeight}}")[{{.Meta.ContactName}}]],{{end}}
    {{if and .Config.Folio.Manuscript.TitlePage.IncludeAddress .Meta.Address}}[#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}}, weight: "{{.Config.Folio.Manuscript.ContactFontWeight}}")[{{.Meta.Address}}]],{{end}}
    {{if and .Config.Folio.Manuscript.TitlePage.IncludePhone .Meta.Phone}}[#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}}, weight: "{{.Config.Folio.Manuscript.ContactFontWeight}}")[{{.Meta.Phone}}]],{{end}}
    {{if and .Config.Folio.Manuscript.TitlePage.IncludeEmail .Meta.Email}}[#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}}, weight: "{{.Config.Folio.Manuscript.ContactFontWeight}}")[{{.Meta.Email}}]],{{end}}
    {{if and .Config.Folio.Manuscript.TitlePage.IncludeWebsite .Meta.Website}}[#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}}, weight: "{{.Config.Folio.Manuscript.ContactFontWeight}}")[{{.Meta.Website}}]],{{end}}
  )
]
{{end}}
{{if .TitleAlignExpr}}#place({{.TitleAlignExpr}}{{if .TitleFloatable}}, float: true{{end}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeTitle}}
  #text(
    font: "{{.Config.Folio.Manuscript.TitleFont}}",
    size: {{.Config.Folio.Manuscript.TitleFontSize}},
    weight: "{{.Config.Folio.Manuscript.TitleFontWeight}}",
  )[{{.Meta.Title}}]
  {{end}}
]{{end}}
{{if .SubtitleAlignExpr}}#place({{.SubtitleAlignExpr}}{{if .SubtitleFloatable}}, float: true{{end}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeSubtitle}}#if "{{.Meta.Subtitle}}" != "" [
    #text(
      font: "{{.Config.Folio.Manuscript.SubtitleFont}}",
      size: {{.Config.Folio.Manuscript.SubtitleFontSize}},
      weight: "{{.Config.Folio.Manuscript.SubtitleFontWeight}}",
      style: "{{.Config.Folio.Manuscript.SubtitleFontStyle}}",
    )[{{.Meta.Subtitle}}]
  ]{{end}}
]{{end}}
{{if .AuthorAlignExpr}}#place({{.AuthorAlignExpr}}{{if .AuthorFloatable}}, float: true{{end}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeAuthor}}#if "{{.Meta.Author}}" != "" [
    #text(font: "{{.Config.Folio.Manuscript.AuthorFont}}", size: {{.Config.Folio.Manuscript.AuthorFontSize}}, weight: "{{.Config.Folio.Manuscript.AuthorFontWeight}}")[{{if .Meta.AuthorAttribution}}{{.Meta.AuthorAttribution}} {{end}}{{.Meta.Author}}]
  ]{{end}}
]{{end}}
{{if .DateAlignExpr}}#place({{.DateAlignExpr}}{{if .DateFloatable}}, float: true{{end}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeDate}}#text(font: "{{.Config.Folio.Manuscript.DateFont}}", size: {{.Config.Folio.Manuscript.DateFontSize}}, weight: "{{.Config.Folio.Manuscript.DateFontWeight}}")[{{.Meta.Date}}]{{end}}
]{{end}}
{{if .WordCountAlignExpr}}#place({{.WordCountAlignExpr}}{{if .WordCountFloatable}}, float: true{{end}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeWordCount}}#text(font: "{{.Config.Folio.Manuscript.WordCountFont}}", size: {{.Config.Folio.Manuscript.WordCountFontSize}}, weight: "{{.Config.Folio.Manuscript.WordCountFontWeight}}")[{{.Meta.WordCount}}]{{end}}
]{{end}}
{{if .VersionAlignExpr}}#place({{.VersionAlignExpr}}{{if .VersionFloatable}}, float: true{{end}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeVersion}}#text(font: "{{.Config.Folio.Manuscript.VersionFont}}", size: {{.Config.Folio.Manuscript.VersionFontSize}}, weight: "{{.Config.Folio.Manuscript.VersionFontWeight}}")[{{.Meta.Version}}]{{end}}
]{{end}}
#align({{.TitleBlockAlignExpr}})[
  {{if and .Config.Folio.Manuscript.TitlePage.IncludeTitle (not .TitleAlignExpr)}}
  #text(
    font: "{{.Config.Folio.Manuscript.TitleFont}}",
    size: {{.Config.Folio.Manuscript.TitleFontSize}},
    weight: "{{.Config.Folio.Manuscript.TitleFontWeight}}",
  )[{{.Meta.Title}}]
  {{end}}
  {{if and .Config.Folio.Manuscript.TitlePage.IncludeSubtitle (not .SubtitleAlignExpr)}}#if "{{.Meta.Subtitle}}" != "" [
    #v(1em)
    #text(
      font: "{{.Config.Folio.Manuscript.SubtitleFont}}",
      size: {{.Config.Folio.Manuscript.SubtitleFontSize}},
      weight: "{{.Config.Folio.Manuscript.SubtitleFontWeight}}",
      style: "{{.Config.Folio.Manuscript.SubtitleFontStyle}}",
    )[{{.Meta.Subtitle}}]
  ]{{end}}
  {{if and .Config.Folio.Manuscript.TitlePage.IncludeAuthor (not .AuthorAlignExpr)}}#if "{{.Meta.Author}}" != "" [
    #v(2em)
    #text(font: "{{.Config.Folio.Manuscript.AuthorFont}}", size: {{.Config.Folio.Manuscript.AuthorFontSize}}, weight: "{{.Config.Folio.Manuscript.AuthorFontWeight}}")[{{if .Meta.AuthorAttribution}}{{.Meta.AuthorAttribution}} {{end}}{{.Meta.Author}}]
  ]{{end}}
]

{{if and .IsUS (not .WordCountAlignExpr)}}
{{if .Config.Folio.Manuscript.TitlePage.IncludeWordCount}}#if "{{.Meta.WordCount}}" != "" [
  #place(bottom + center, float: true)[
    #text(font: "{{.Config.Folio.Manuscript.WordCountFont}}", size: {{.Config.Folio.Manuscript.WordCountFontSize}}, weight: "{{.Config.Folio.Manuscript.WordCountFontWeight}}")[{{.Meta.WordCount}}]
  ]
]{{end}}
{{end}}

{{if .Config.Folio.Manuscript.TOC.PageBreakBefore}}#pagebreak(){{end}}
{{end}}

{{if .Config.Folio.Manuscript.TOC.Enabled}}
// Clear the title-page footer before the TOC's blank-page-before directive so any inserted
// parity blank does not inherit the British title-page grid footer.
#set page(numbering: none, footer: none)
{{.Config.Folio.Manuscript.TOC.BlankPageBefore.TypstDirective}}
#text(
  font: "{{.Config.Folio.Manuscript.TOC.HeadingFont}}",
  size: {{.Config.Folio.Manuscript.TOC.HeadingFontSize}},
  weight: "{{.Config.Folio.Manuscript.TOC.HeadingFontWeight}}",
)[{{.Config.Folio.Manuscript.TOC.Title}}]
#v(1em)
#text(font: "{{.Config.Folio.Manuscript.TOC.Font}}", size: {{.Config.Folio.Manuscript.TOC.FontSize}}, weight: "{{.Config.Folio.Manuscript.TOC.FontWeight}}")[
  #set par(leading: {{.Config.Folio.Manuscript.TOC.LineSpacing}})
  #show outline.entry: it => block(
    above: if it.level == 1 { {{.Config.Folio.Manuscript.TOC.PartGapBefore}} } else { 0pt },
    below: 0.5em,
  )[
    #if it.level == 1 and {{.Config.Folio.Manuscript.TOC.PartBold}} {
      strong[#it]
    } else {
      it
    }
  ]
  #outline(title: none)
]
#pagebreak()
{{.Config.Folio.Manuscript.TOC.BlankPageAfter.TypstDirective}}
{{end}}

// counter(page) is intentionally NOT reset here. The physical counter continues from
// the title-page count so parity checks (calc.odd, pagebreak(to: "odd")) evaluate against
// the reader's view of the book (page 1 = title = recto). The visible page number seen by
// the reader in the running footer is derived through #folio-display-page() which subtracts
// the offset recorded at the first body block.
#set text(
  top-edge: 0.8em,
  bottom-edge: -0.2em,
)
#set par(
  first-line-indent: {{.Config.Folio.Manuscript.ParagraphIndent}},
  spacing: {{.Spacing}},
  leading: {{.Leading}},
)
#set page(
  {{if .PageSpec.Custom}}width: {{.PageSpec.Width}}, height: {{.PageSpec.Height}},{{else}}paper: "{{.PageSpec.Named}}",{{end}}
  {{if .Config.Folio.Manuscript.PageHeader.Enabled}}margin: (
    top: {{.Config.Folio.Manuscript.PageHeader.DistanceFromEdge}} + {{.Config.Folio.Manuscript.PageHeader.ContentPaddingAfter}},
    {{if .PageFooterEnabled}}bottom: {{.Config.Folio.Manuscript.PageFooter.DistanceFromEdge}} + {{.Config.Folio.Manuscript.PageFooter.ContentPaddingAfter}},{{end}}
    {{if .GutterActive}}inside: {{.Config.Folio.Manuscript.Margin}} + {{.Gutter}},
    outside: {{.Config.Folio.Manuscript.Margin}},{{else}}rest: {{.Config.Folio.Manuscript.Margin}},{{end}}
  ),
  header-ascent: {{.Config.Folio.Manuscript.PageHeader.ContentPaddingAfter}},
  {{if .PageFooterEnabled}}footer-descent: {{.Config.Folio.Manuscript.PageFooter.ContentPaddingAfter}},{{end}}{{else}}margin: (
    {{if .PageFooterEnabled}}bottom: {{.Config.Folio.Manuscript.PageFooter.DistanceFromEdge}} + {{.Config.Folio.Manuscript.PageFooter.ContentPaddingAfter}},{{end}}
    {{if .GutterActive}}inside: {{.Config.Folio.Manuscript.Margin}} + {{.Gutter}},
    outside: {{.Config.Folio.Manuscript.Margin}},{{else}}rest: {{.Config.Folio.Manuscript.Margin}},{{end}}
  ),
  {{if .PageFooterEnabled}}footer-descent: {{.Config.Folio.Manuscript.PageFooter.ContentPaddingAfter}},{{end}}{{end}}
  numbering: none,
  {{if .PageFooterEnabled}}footer: context {
    let pg = counter(page).at(here()).first()
    if pg in state("folio-skip-footer-pages", ()).final() {
      none
    } else {
      align({{.FooterAlignExpr}})[
        #text(
          font: "{{.Config.Folio.Manuscript.PageFooter.Font}}",
          size: {{.Config.Folio.Manuscript.PageFooter.FontSize}},
          weight: "{{.Config.Folio.Manuscript.PageFooter.FontWeight}}",
        )[{{.Footer}}]
      ]
    }
  },{{else}}footer: none,{{end}}
  {{if .Config.Folio.Manuscript.PageHeader.Enabled}}header: context {
    let pg = counter(page).at(here()).first()
    if pg in state("folio-skip-header-pages", ()).final() {
      none
    } else {
      align({{.HeaderAlignExpr}})[
        #text(
          font: "{{.Config.Folio.Manuscript.PageHeader.Font}}",
          size: {{.Config.Folio.Manuscript.PageHeader.FontSize}},
          weight: "{{.Config.Folio.Manuscript.PageHeader.FontWeight}}",
        )[{{.Header}}]
      ]
    }
  },{{else}}header: none,{{end}}
)

{{.Body}}
