// Generated by First Folio.

#let folio-section(body) = {
  v(1.2em)
  align(left)[#text(
    font: "{{.Config.Folio.Manuscript.HeadingFont}}",
    size: {{.Config.Folio.Manuscript.HeadingFontSize}},
    weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
  )[#body]]
  v(0.4em)
}

#let folio-part(first: false, body) = {
  if not first {
    pagebreak()
  }
  align({{.Config.Folio.Manuscript.Part.Align}} + horizon)[
    #text(
      font: "{{.Config.Folio.Manuscript.HeadingFont}}",
      size: {{.Config.Folio.Manuscript.HeadingFontSize}},
      weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
    )[
      #heading(level: 1)[#body]
    ]
  ]
}

#let folio-chapter(first: false, body) = {
  if not first {
    pagebreak()
  }
  v(30%)
  align({{.Config.Folio.Manuscript.Chapter.Align}})[
    #text(
      font: "{{.Config.Folio.Manuscript.HeadingFont}}",
      size: {{.Config.Folio.Manuscript.HeadingFontSize}},
      weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
    )[
      #heading(level: 2)[#body]
    ]
  ]
  v({{.Config.Folio.Manuscript.Chapter.SpaceAfter}})
}

#let folio-scene-break() = {
  v(1em)
  align(center)[\* \* \*]
  v(1em)
}

#let folio-code(body) = {
  block[
    #text(font: "{{.Config.Folio.Manuscript.MonoFont}}", size: {{.Config.Folio.Manuscript.MonoFontSize}})[#body]
  ]
}

#set page(
  paper: "{{.Config.Folio.Manuscript.Page}}",
  margin: {{.Config.Folio.Manuscript.Margin}},
  numbering: none,
)

#set text(font: "{{.Config.Folio.Manuscript.Font}}", size: {{.Config.Folio.Manuscript.FontSize}})
#set par(
  first-line-indent: {{.Config.Folio.Manuscript.ParagraphIndent}},
  spacing: {{.Spacing}},
  leading: {{.Leading}},
)

{{if not .IsUS}}
#set page(
  footer: [
    #grid(
      columns: (1fr, 1fr, 1fr),
      align: (left, center, right),
      [
        #text(font: "{{.Config.Folio.Manuscript.VersionFont}}", size: {{.Config.Folio.Manuscript.VersionFontSize}})[{{.Meta.Version}}]
      ],
      [
        #text(font: "{{.Config.Folio.Manuscript.WordCountFont}}", size: {{.Config.Folio.Manuscript.WordCountFontSize}})[
          #if "{{.Meta.WordCount}}" != "" [{{.Meta.WordCount}} words]
        ]
      ],
      [
        #text(font: "{{.Config.Folio.Manuscript.DateFont}}", size: {{.Config.Folio.Manuscript.DateFontSize}})[{{.Meta.Date}}]
      ],
    )
  ],
)
{{end}}

#place(top + left, float: true)[
  #stack(
    dir: ttb,
    spacing: 0.25em,
    [#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}})[{{.Meta.Author}}]],
    [#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}})[{{.Meta.Address}}]],
    [#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}})[{{.Meta.Phone}}]],
    [#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}})[{{.Meta.Email}}]],
    [#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}})[{{.Meta.Website}}]],
  )
]
{{if .IsUS}}
#place(top + right, float: true)[
  #if "{{.Meta.WordCount}}" != "" [
    #text(font: "{{.Config.Folio.Manuscript.WordCountFont}}", size: {{.Config.Folio.Manuscript.WordCountFontSize}})[{{.Meta.WordCount}} words]
  ]
]
{{end}}
#align(center + horizon)[
  #text(
    font: "{{.Config.Folio.Manuscript.TitleFont}}",
    size: {{.Config.Folio.Manuscript.TitleFontSize}},
    weight: "{{.Config.Folio.Manuscript.TitleFontWeight}}",
  )[{{.Meta.Title}}]
  #if "{{.Meta.Subtitle}}" != "" [
    #v(1em)
    #text(
      font: "{{.Config.Folio.Manuscript.SubtitleFont}}",
      size: {{.Config.Folio.Manuscript.SubtitleFontSize}},
      style: "{{.Config.Folio.Manuscript.SubtitleFontStyle}}",
    )[{{.Meta.Subtitle}}]
  ]
  #if "{{.Meta.Author}}" != "" [
    #v(2em)
    #text(font: "{{.Config.Folio.Manuscript.AuthorFont}}", size: {{.Config.Folio.Manuscript.AuthorFontSize}})[{{.Meta.AuthorAttribution}} {{.Meta.Author}}]
  ]
]

#pagebreak()

{{if .Config.Folio.Manuscript.TOC.Enabled}}
#set page(numbering: none, footer: none)
#text(
  font: "{{.Config.Folio.Manuscript.TOC.HeadingFont}}",
  size: {{.Config.Folio.Manuscript.TOC.HeadingFontSize}},
  weight: "{{.Config.Folio.Manuscript.TOC.HeadingFontWeight}}",
)[{{.Config.Folio.Manuscript.TOC.Title}}]
#v(1em)
#text(font: "{{.Config.Folio.Manuscript.TOC.Font}}", size: {{.Config.Folio.Manuscript.TOC.FontSize}})[
  #set par(leading: 0.5em)
  #show outline.entry: it => block(below: 0.5em)[#it]
  #outline(title: none)
]
#pagebreak()
{{end}}

#counter(page).update(1)
#set page(
  paper: "{{.Config.Folio.Manuscript.Page}}",
  margin: {{.Config.Folio.Manuscript.Margin}},
  numbering: none,
  footer: none,
  header: align(right)[
    #pad(right: 0.5em)[
      #text(
        font: "{{.Config.Folio.Manuscript.PageHeader.Font}}",
        size: {{.Config.Folio.Manuscript.PageHeader.FontSize}},
        weight: "{{.Config.Folio.Manuscript.PageHeader.FontWeight}}",
      )[{{.Header}}]
    ]
  ],
)

{{.Body}}
