// ABOUTME: Typst layout template for stage-play PDF and Typst output.
// ABOUTME: Receives validated layout values and escaped semantic body markup from Go.
// Generated by First Folio
#set page(paper: "{{.Page}}", margin: {{.Margin}}, numbering: "1", number-align: center + bottom)
#set text(font: "{{.Font}}", size: {{.FontSize}}{{.GlobalWeight}}{{.GlobalStretch}})
#set par(leading: 0.6em)

{{if .DialogueSameLine}}
#let dialogue(name, direction: none, body) = {
  block(above: {{.SpeechSpace}}, below: 0.2em, breakable: true)[
    #grid(
      columns: ({{.DialogueWrap}}, 1fr),
      gutter: 0pt,
      [#text(weight: "{{.SpeakerWeight}}")[{{.SpeakerContent}}]],
      [
        #if direction != none [
          {{.InstructionOpen}}{{.InstructionPrefix}}#direction{{.InstructionSuffix}}{{.InstructionClose}} \
        ]
        #body
      ],
    )
  ]
}
{{else}}
#let dialogue(name, direction: none, body) = {
  block(above: {{.SpeechSpace}}, below: 0.2em, breakable: true, spacing: 0em)[
    #set par(spacing: 0.6em)
    #pad(left: {{.DialogueIndent}}, right: {{.DialogueWrap}})[
      #pad(left: {{.SpeakerIndent}})[#align({{.SpeakerAlign}})[#text(weight: "{{.SpeakerWeight}}")[{{.SpeakerContent}}]]]
      #if direction != none [
        #align({{.InstructionAlign}})[{{.InstructionOpen}}{{.InstructionPrefix}}#direction{{.InstructionSuffix}}{{.InstructionClose}}]
      ]
      #body
    ]
  ]
}
{{end}}

#let stage-direction(body) = {
  block(above: {{.DirectionSpace}}, below: 0.6em)[
    #pad(left: {{.DirectionIndent}})[#align({{.DirectionAlign}})[{{.DirectionOpen}}#body{{.DirectionClose}}]]
  ]
}

#let act-header(title) = {
  v({{.ActSpace}})
  align({{.ActAlign}})[#text(font: "{{.ActFont}}", size: {{.ActSize}}, weight: "{{.ActWeight}}")[{{.ActOpen}}#title{{.ActClose}}]]
  v(0.3em)
}

#let scene-header(title) = {
  v({{.SceneSpace}})
  align({{.SceneAlign}})[#text(font: "{{.SceneFont}}", size: {{.SceneSize}}, weight: "{{.SceneWeight}}")[{{.SceneOpen}}#title{{.SceneClose}}]]
  v({{.SceneAfter}})
}

#let frontmatter-header(title) = {
  v({{.FrontmatterSpace}})
  align({{.FrontmatterAlign}})[#text(size: {{.FrontmatterSize}}, weight: "{{.FrontmatterWeight}}")[#title]]
}

#let prop-text(body) = {
  v(1.6em)
  align(center)[#text(style: "italic", weight: "bold")[#body]]
  v(0.6em)
}

{{if .HasTitle}}
#set page(numbering: {{if .TitlePageNumber}}"1"{{else}}none{{end}}, footer: grid(
  columns: (1fr, 1fr),
  align: (left, right),
  [{{.FooterLeft}}],
  [{{.FooterRight}}],
))
#align({{.TitleAlign}})[
  #v({{.TitleOffset}})
  #text(font: "{{.TitleFont}}", size: {{.TitleSize}}, weight: "{{.TitleWeight}}", style: "{{.TitleStyle}}")[{{.Title}}]
  {{if .HasSubtitle}}
  #v({{.SubtitleSpace}})
  #text(font: "{{.SubtitleFont}}", size: {{.SubtitleSize}}, style: "{{.SubtitleStyle}}")[{{.Subtitle}}]
  {{end}}
  {{if .HasAuthor}}
  {{if .AuthorPrefixLines}}
  #v({{.AuthorSpace}})
  {{range $index, $line := .AuthorPrefixLines}}
  {{if $index}}#v(0.3em){{end}}
  #text(font: "{{$.AuthorFont}}", size: {{$.AuthorSize}})[{{$line}}]
  {{end}}
  #v(0.3em)
  #text(font: "{{.AuthorFont}}", size: {{.AuthorSize}}, style: "{{.AuthorStyle}}")[{{.Author}}]
  {{else}}
  #v({{.AuthorSpace}})
  #text(font: "{{.AuthorFont}}", size: {{.AuthorSize}}, style: "{{.AuthorStyle}}")[{{.AuthorPrefixInline}}{{.Author}}]
  {{end}}
  {{end}}
]
#pagebreak()
#set page(numbering: "1", number-align: center + bottom, footer: auto)
{{end}}

{{.Body}}
