// ABOUTME: Typst layout template for stage-play PDF and Typst output.
// ABOUTME: Receives validated layout values and escaped semantic body markup from Go.
// Generated by First Folio
#set page(paper: "{{.Page}}", margin: {{.Margin}}, numbering: "1", number-align: center + bottom)
#set text({{.RootFont.Args}})
#show heading: set text({{.HeadingFont.Args}})
#set par(leading: 0.6em)

{{if .DialogueSameLine}}
#let dialogue(name, direction: none, body) = {
  block(above: {{.SpeechSpace}}, below: 0.2em, breakable: true)[
    #grid(
      columns: ({{.DialogueWrap}}, 1fr),
      gutter: 0pt,
      [#text({{.SpeakerFont.Args}})[{{.SpeakerContent}}]],
      [
        #if direction != none [
          #text({{.InstructionFont.Args}})[{{.InstructionPrefix}}#direction{{.InstructionSuffix}}] \
        ]
        #text({{.DialogueFont.Args}})[#body]
      ],
    )
  ]
}
{{else}}
#let dialogue(name, direction: none, body) = {
  block(above: {{.SpeechSpace}}, below: 0.2em, breakable: true, spacing: 0em)[
    #set par(spacing: 0.6em)
    #pad(left: {{.DialogueIndent}}, right: {{.DialogueWrap}})[
      #pad(left: {{.SpeakerIndent}})[#align({{.SpeakerAlign}})[#text({{.SpeakerFont.Args}})[{{.SpeakerContent}}]]]
      #if direction != none [
        #align({{.InstructionAlign}})[#text({{.InstructionFont.Args}})[{{.InstructionPrefix}}#direction{{.InstructionSuffix}}]]
      ]
      #text({{.DialogueFont.Args}})[#body]
    ]
  ]
}
{{end}}

#let stage-direction(body) = {
  block(above: {{.DirectionSpace}}, below: 0.6em)[
    #pad(left: {{.DirectionIndent}})[#align({{.DirectionAlign}})[#text({{.DirectionFont.Args}})[#body]]]
  ]
}

#let transition(body) = {
  v({{.TransitionSpace}})
  pad(left: {{.TransitionIndent}})[#align({{.TransitionAlign}})[#text({{.TransitionFont.Args}})[#body]]]
}

#let act-header(title) = {
  v({{.ActSpace}})
  align({{.ActAlign}})[#text({{.ActFont.Args}})[{{.ActOpen}}#title{{.ActClose}}]]
  v(0.3em)
}

#let scene-header(title) = {
  v({{.SceneSpace}})
  align({{.SceneAlign}})[#text({{.SceneFont.Args}})[{{.SceneOpen}}#title{{.SceneClose}}]]
  v({{.SceneAfter}})
}

#let frontmatter-header(title) = {
  v({{.FrontmatterSpace}})
  align({{.FrontmatterAlign}})[#text({{.FrontmatterFont.Args}})[#title]]
}

#let prop-text(body) = {
  v(1.6em)
  align(center)[#text(style: "italic", weight: "bold")[#body]]
  v(0.6em)
}

{{if .HasTitle}}
#set page(numbering: {{if .TitlePageNumber}}"1"{{else}}none{{end}}, footer: grid(
  columns: (1fr, 1fr),
  align: (left, right),
  [{{.FooterLeft}}],
  [{{.FooterRight}}],
))
#align({{.TitleAlign}})[
  #v({{.TitleOffset}})
  #text({{.TitleFont.Args}})[{{.Title}}]
  {{if .HasSubtitle}}
  #v({{.SubtitleSpace}})
  #text({{.SubtitleFont.Args}})[{{.Subtitle}}]
  {{end}}
  {{if .HasAuthor}}
  {{if .AuthorPrefixLines}}
  #v({{.AuthorSpace}})
  {{range $index, $line := .AuthorPrefixLines}}
  {{if $index}}#v(0.3em){{end}}
  #text({{$.AuthorFont.Args}})[{{$line}}]
  {{end}}
  #v(0.3em)
  #text({{.AuthorFont.Args}})[{{.Author}}]
  {{else}}
  #v({{.AuthorSpace}})
  #text({{.AuthorFont.Args}})[{{.AuthorPrefixInline}}{{.Author}}]
  {{end}}
  {{end}}
]
#pagebreak()
#set page(numbering: "1", number-align: center + bottom, footer: auto)
{{end}}

{{.Body}}
